securityeventsexplorer/app_see/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'app-see'

urlpatterns = [
    path('', views.security_events_explorer, name='security_events_explorer'),
    path('see_orchestrator', views.see_orchestrator, name='see_orchestrator'),
]

securityeventsexplorer/securityeventsexplorer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls), #disable access to admin web console
    path('', include('app_see.urls', namespace='app-see')),
]

securityeventsexplorer/app_see/views.py
from django.shortcuts import render
import logging

logger = logging.getLogger('debug.log')

def security_events_explorer(request):
    return render(request, 'app_see/see.html')

def see_orchestrator(request):
    return render(request, 'app_see/see_orchestrator.html')

securityeventsexplorer/app_see/templates/app_see/see.html
{% extends "app_see/see_base.html" %}

{% block head %}
    {% load static %}
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
    <link href="{% static 'app_see/style/filepond.css' %}" rel="stylesheet"> 
    <script src="{% static 'app_see/js/sse_orchestrator.js'%}"></script> 
    <script src="{% static 'app_see/js/filepond.js' %}"></script>   
    <script src="{% static 'app_see/js/jquery-3.6.0.min.js' %}"></script>  
    <script src="{% static 'app_see/js/see.js' %}"></script>   
    <script src="{% static 'app_see/js/security events.js' %}"></script>   
    <script src="{% static 'app_see/js/see_report_creator.js' %}"></script>   
    <script src="{% static 'app_see/js/sse_options.js' %}"></script>   
    <script src="{% static 'app_see/js/html2canvas.min.js' %}"></script>   
    <script src="{% static 'app_see/js/pdfmake.min.js' %}"></script>   
    <script src="{% static 'app_see/js/vfs_fonts.js' %}"></script>  
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script> 
{% endblock %}

{% block content %}
    <div class="row show-grid full-height   ">
	    <div class="col-md-3 options_section"></div>
      	    <div id="main-options-section" class="col-md-6 options_section"></div>
	    <div class="col-md-3 options_section"></div>
    </div>
    
    <div class="row show-grid full-height   ">
	    <div class="col-md-1 options_section"></div>
      	    <div id="main-options-section" class="col-md-10 options_section">     
				<div class="w3-sidebar w3-bar-block w3-tbm w3-card" style="width:130px;height: 300px; height: 100%; background-color: rgba(8, 11, 12, 1) !important;">
					<button class="w3-bar-item w3-button tablink" onclick="openSectionByDirectClick(event, 'Upload')"><b>UPLOAD</b></button>
					<button id="OptionsBtn" class="w3-bar-item w3-button tablink" onclick="openSectionByDirectClick(event, 'Options')" disabled><b>OPTIONS</b></button>
					<button id="OrchestratorBtn" class="w3-bar-item w3-button tablink" onclick="openSectionByDirectClick(event, 'Orchestrator')" disabled><b>ORCHESTRATOR</b></button>
					<button id="DrawBtn" class="w3-bar-item w3-button tablink" onclick="openSectionByDirectClick(event, 'Draw')" disabled><b>DRAW</b></button>
					<button id="ExportBtn" class="w3-bar-item w3-button tablink" onclick="openSectionByDirectClick(event, 'Export')" disabled><b>EXPORT</b></button>
				</div>

				<div style="margin-left:130px; height: calc(100vh - 100px);">
					<div id="Upload" class="w3-container city w3-animate-opacity wse-content-box" style="overflow:auto; height:100%; background-color: hsl(220, 25%, 10%);">
						<h4 id="app-description">
						<b>Windows Security Explorer</b> is a security tool that lets you navigate the  Windows Security Events in a 
						user-friendly fashion. To start, export the Windows security logs in XML format and upload them to your browser
						using the button below. All the magic happens in your browser, so no logs are sent over the Internet for any purpose.
						</h4>   
						<input id="uploaded-wse-logs" type="file" class="filepond">  
						<button type="button" id="upload-ws-logs" class="btn btn-primary build_timeline">Upload</button>
					</div>

					<div id="Options" class="w3-container city w3-animate-opacity wse-content-box" style="display:none; overflow:auto; height:100%; background-color: hsl(220, 25%, 10%) ;" >
					</div>

					<div id="Orchestrator" class="w3-container city w3-animate-opacity wse-content-box" style="display:none; overflow:auto; height:100%; background-color: hsl(220, 25%, 10%) ;" >
					</div>

					<div id="Draw" class="w3-container city w3-animate-opacity wse-content-box" style="display:none; overflow:auto; height:100%; background-color: hsl(220, 25%, 10%) ;">
						<div id="visualization"></div>
					</div>

					<div id="Export" class="w3-container city w3-animate-opacity wse-content-box" style="display:none; overflow:auto; height:100%; background-color: hsl(220, 25%, 10%) ;">
					</div>
				</div>		    	
	    	</div>
	    <div class="col-md-1 options_section"></div>
    </div>
    
    <div class="row show-grid">
      <div class="col-md-12 timeline_section"></div>
    </div>
{% endblock content %}

securityeventsexplorer/app_see/templates/app_see/see_base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet"  href="{% static 'app_see/style/style.css'%}" />
    <link rel="stylesheet"  href="{% static 'app_see/style/timeline.css'%}" />
    <link href="{% static 'app_see/style/saira-extra-condensed.css'%}" rel="stylesheet" type="text/css">    
    <link href="{% static 'app_see/style/gugi.css'%}"  rel="stylesheet" type="text/css">
    <title>Security Events Explorer</title>
    <script type="text/javascript" src="{% static 'app_see/js/vis-timeline-graph2d.min.js'%}"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}  
    {% block head %}{% endblock %}    
    <script type="text/javascript"src=https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'app_see/style/daterangepicker.css'%}" />  
    <link href="{% static 'app_see/style/vis-timeline-graph2d.min.css'%}" rel="stylesheet" type="text/css" />
  </head>
  
  <body>    
    <nav class="navbar-home navbar navbar-default navbar-static-top">
      <div class="container">          
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <img src = "{% static 'app_see/images/logo.png'  %}" class="navbar-brand" style="padding: 10px 15px 10px 15px;"  >
          <a class="navbar-brand" href="{% url 'app-see:security_events_explorer' %}">
                    Security Events Explorer</a>
        </div>        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'app-see:security_events_explorer' %}">App</a></li>
            <li><a href="{% url 'app-see:security_events_explorer' %}">Documentation</a></li>
            <li><a href="{% url 'app-see:security_events_explorer' %}">Downloads</a></li>
            <li><a href="{% url 'app-see:security_events_explorer' %}">Contacts</a></li>
          </ul>          
        </div>        
      </div>
    
    </nav>
    <div class="container-fluid ">
      <div>
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>

securityeventsexplorer/app_see/templates/app_see/see_orchestrator.html
{% load static %}
{% load bootstrap3 %}
 
<!DOCTYPE html>
<html>
    <head>    
        {% load static %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %} 
        <title>Security Events Explorer Orchestrator</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap" rel="stylesheet">
        <link href="{% static 'app_see/style/orchestrator_styles.css'%}" rel='stylesheet' type='text/css'>
        <link href="{% static 'app_see/style/orchestrator_flowy.css'%}"  rel='stylesheet' type='text/css'>    
        <script src="{% static 'app_see/js/orchestrator.flowy.js' %}"></script>
        <script src="{% static 'app_see/js/orchestrator.main.js'%}"></script>   
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    </head>
    <body>
        <div id="leftcard">
            <p id="header">Blocks</p>
            <div id="subnav">
                <div id="events" class="navactive side">Events</div>
                <div id="filters" class="navdisabled side">Filters</div>
            </div>
            <div id="blocklist">
            </div>
        </div>
        <div id="propwrap">
            <div id="properties">
                <div id="close">
                    <img src="{% static 'app_see/images/assets/close.svg' %}">
                </div>
                <p id="header2">Properties</p>
                <div id="proplist">
                </div>
                <div id="divisionthing"></div>
                <div id="removeblock">Delete All Blocks</div>
            </div>
        </div>
        <div id="canvas">
        </div>
    </body>
</html>